/**
 * Builds every derivative of the Mikasa mark from one source file.
 *
 * Source: assets/logo.svg (the designer's export, not served).
 * Outputs: components/mikasa-mark.tsx, app/icon.svg, app/apple-icon.png,
 *          public/og/logo.png
 *
 * Two things this does beyond copying paths:
 *
 * 1. Rounds coordinates to two decimals. The export carries five and six
 *    (`M25.0874 7.11255C23.4702 …`) on a 51-unit viewBox rendered at 38px,
 *    where two decimals is 0.015px of error — invisible, and the extra
 *    digits cost about 1.7KB brotli on every single page because the mark
 *    is inlined in the header and footer of all of them.
 *
 * 2. Drops the per-path fills. The export paints everything #D7CFC7, a pale
 *    grey that vanishes on parchment and reads as dirt on the dark footer.
 *    The component inherits `currentColor` instead, so one copy of the
 *    artwork serves the header, the footer and the icons.
 *
 * Re-run after the designer supplies new artwork:
 *   node scripts/make-logo.mjs
 */
import sharp from "sharp";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const SOURCE = path.join(ROOT, "assets", "logo.svg");

/** Brand ground for the icons, from --color-cherry in app/globals.css. */
const CHERRY = "#8b2635";
/** Mark colour on that ground, from --color-parchment. */
const PARCHMENT = "#f7f1e6";

const svg = readFileSync(SOURCE, "utf8");

/** Trim every number in path data to `dp` decimals. */
function round(d, dp = 2) {
  return d.replace(/-?\d*\.\d+/g, (n) => String(Number(parseFloat(n).toFixed(dp))));
}

const paths = [...svg.matchAll(/<path\s+d="([^"]+)"[^>]*\/>/g)].map((m) => round(m[1]));
if (!paths.length) throw new Error(`no <path> elements found in ${SOURCE}`);

const before = svg.match(/ d="([^"]+)"/g).join("").length;
const after = paths.join("").length;

// ---- 1. The React component ------------------------------------------------

writeFileSync(
  path.join(ROOT, "components", "mikasa-mark.tsx"),
  `/**
 * The Mikasa mark.
 *
 * GENERATED by scripts/make-logo.mjs from assets/logo.svg — edit neither this
 * file nor app/icon.svg by hand; change the source and re-run the script, or
 * the copies drift apart.
 *
 * Inherits \`currentColor\` so the same artwork works in ink beside the
 * wordmark and in parchment on the dark footer. Decorative: every call site
 * already names itself through the surrounding link.
 */
export function MikasaMark({
  size = 38,
  className,
  style,
}: {
  size?: number;
  className?: string;
  style?: React.CSSProperties;
}) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 51 51"
      fill="currentColor"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      className={className}
      style={style}
    >
${paths.map((d) => `      <path d="${d}" />`).join("\n")}
    </svg>
  );
}
`
);

// ---- 2. The favicon --------------------------------------------------------

// On transparency the mark is invisible in a light browser tab — it is an
// outline drawing, not a solid shape. The filled ground is what makes it
// legible at 16px. Scaled to 86% so it does not touch the rounded corners.
const iconSvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 51 51" width="51" height="51">
  <rect width="51" height="51" rx="11" fill="${CHERRY}"/>
  <g fill="${PARCHMENT}" transform="translate(25.5 25.5) scale(0.86) translate(-25.5 -25.5)">
${paths.map((d) => `    <path d="${d}"/>`).join("\n")}
  </g>
</svg>
`;
writeFileSync(path.join(ROOT, "app", "icon.svg"), iconSvg);

// ---- 3. Raster icons -------------------------------------------------------

mkdirSync(path.join(ROOT, "public", "og"), { recursive: true });

// 180px for the iOS home screen; 512px for schema.org Organization.logo,
// which Google wants as a crawlable raster at a stable URL (app/icon.svg is
// served from a content-hashed path, so it cannot be cited in JSON-LD).
const rasters = [
  { out: path.join(ROOT, "app", "apple-icon.png"), size: 180 },
  { out: path.join(ROOT, "public", "og", "logo.png"), size: 512 },
];

for (const { out, size } of rasters) {
  const info = await sharp(Buffer.from(iconSvg), { density: 600 })
    .resize(size, size)
    .png({ compressionLevel: 9 })
    .toFile(out);
  console.log(
    `${path.relative(ROOT, out).replace(/\\/g, "/")}  ${info.width}x${info.height}  ${Math.round(info.size / 1024)} KB`
  );
}

console.log(`components/mikasa-mark.tsx  ${paths.length} paths`);
console.log(`app/icon.svg`);
console.log(
  `\npath data: ${before} -> ${after} bytes (${Math.round((1 - after / before) * 100)}% smaller, inlined twice on every page)`
);
